name: Datalab

on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Datalab
    steps:
    - name: Hello world action step
      id: grade
      uses: pamoreno/datalab-action@v1
      with:
        target: 'grade'
    # Use the output from the `hello` step
    - name: Get the output log
      run: echo "The result was ${{ steps.grade.outputs.result }}"
